#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

ECHO_PREPEND="${0##*/} ==>"

echo "$ECHO_PREPEND START"

# ensure everything in the app is up to date.
script/update

echo "$ECHO_PREPEND END"
